version: "3.8"

services:
    # Jenkins Master
    jenkins:
        build: ./jenkins
        ports:
            - 8085:8080
        volumes:
            - ./jenkins/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /usr/bin/docker:/usr/bin/docker:ro
